openapi: 3.0.3
info:
  title: Simple Employee API
  description: A basic API for managing employee records using CRUD operations.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Production Server

paths:
  /employees:
    get:
      summary: List all employees
      description: Retrieves a list of all employee records.
      operationId: listEmployees
      tags:
        - Employees
      responses:
        "200":
          description: A JSON array of employee objects.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Employee"
    post:
      summary: Create a new employee
      description: Adds a new employee to the database.
      operationId: createEmployee
      tags:
        - Employees
      requestBody:
        description: The employee object to be created.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewEmployee"
      responses:
        "201":
          description: Employee created successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "400":
          description: Invalid input provided.

  /employees/{employeeId}:
    parameters:
      - name: employeeId
        in: path
        required: true
        description: The unique identifier of the employee.
        schema:
          type: string
          format: uuid
    get:
      summary: Get an employee by ID
      description: Retrieves a single employee record by its ID.
      operationId: getEmployeeById
      tags:
        - Employees
      responses:
        "200":
          description: The requested employee record.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "404":
          description: Employee not found.
    put:
      summary: Update an existing employee
      description: Updates the details of an existing employee by their ID.
      operationId: updateEmployee
      tags:
        - Employees
      requestBody:
        description: The updated employee object.
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewEmployee" # Re-using NewEmployee for updates
      responses:
        "200":
          description: Employee updated successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Employee"
        "404":
          description: Employee not found.
    delete:
      summary: Delete an employee
      description: Deletes an employee record by its ID.
      operationId: deleteEmployee
      tags:
        - Employees
      responses:
        "204":
          description:
